version: '3'
services:
  app:
    build: ./app
    ports:
     - "8080:3000"
    volumes: 
     - ./app:/data:z
    depends_on:
     - server 
  server:
    build: ./server
    ports:
     - "7001:7001"
    volumes: 
     - ./server:/data:z
    depends_on:
     - mongo
  mongo:
    image: "mongo"
    volumes:
     - /home/doris/data/azalea_db:/data/db:z
